apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-cabundle
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: tracing-sidecar
spec:
  mode: sidecar
  volumeMounts:
  - name: cabundle-volume
    mountPath: /etc/pki/ca-trust/source/service-ca
    readonly: true
  volumes:
  - name: cabundle-volume
    configMap:
      name: otelcol-cabundle
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 25m
      memory: 25Mi
  config: |
    extensions:
      memory_ballast:
        size_in_percentage: 30
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 25
    exporters:
      otlp:
        endpoint: otelcol-collector-headless.tracing-system.svc:4317
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
    service:
      extensions: [memory_ballast]
      pipelines:
        traces:
          receivers: [otlp,jaeger]
          processors: [memory_limiter, batch]
          exporters: [otlp]
