apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-cabundle
  namespace: tracing-system
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol
  namespace: tracing-system
spec:
  mode: deployment
  volumeMounts:
  - name: cabundle-volume
    mountPath: /etc/pki/ca-trust/source/service-ca
    readonly: true
  - name: tls-config-volume
    mountPath: /etc/tls-config
    readonly: true
  - name: otlp-htpasswd-volume
    mountPath: /etc/otlp
    readonly: true
  volumes:
  - name: cabundle-volume
    configMap:
      name: otelcol-cabundle
  - name: tls-config-volume
    secret:
      secretName: otelcol-collector-headless-tls
  - name: otlp-htpasswd-volume
    secret:
      secretName: otlp-htpasswd
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 50Mi
  # image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.43.0
  image: docker.io/otel/opentelemetry-collector-contrib:0.43.0
  config: |
    extensions:
      basicauth:
        htpasswd:
          file: /etc/otlp/otlp-htpasswd
      memory_ballast:
        size_in_percentage: 30
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              cert_file: /etc/tls-config/tls.crt
              key_file: /etc/tls-config/tls.key
      otlp/auth:
        protocols:
          grpc:
            endpoint: 0.0.0.0:44317
            tls:
              cert_file: /etc/tls-config/tls.crt
              key_file: /etc/tls-config/tls.key
            auth:
              authenticator: basicauth
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 25
    exporters:
      jaeger:
        endpoint: jaeger-collector-headless.tracing-system.svc:14250
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
    service:
      extensions: [memory_ballast, basicauth]
      pipelines:
        traces:
          receivers: [otlp, otlp/auth]
          processors: [memory_limiter, batch]
          exporters: [jaeger]
