apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx-create-span
spec:
  selector:
    matchLabels:
      app: vertx-create-span
  template:
    metadata:
      labels:
        app: vertx-create-span
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
      - name: vertx-create-span
        image: jaegertracing/vertx-create-span:operator-e2e-tests
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
