apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: rhosdt-sample-client-gateway
spec:
  description: |
    An example RHOSDT multi-cluster client gateway collector configuration
  targetResource:
    apiVersion: opentelemetry.io/v1alpha1
    kind: OpenTelemetryCollector
  title: MultiCluster Client Gateway
  yaml: |
    apiVersion: opentelemetry.io/v1alpha1
    kind: OpenTelemetryCollector
    metadata:
      name: gateway
      namespace: tracing-system
    spec:
      mode: deployment
      volumeMounts:
      - name: headless-tls-volume
        mountPath: /headless-tls
        readonly: true
      - name: otlp-ca-volume
        mountPath: /otlp-ca
        readonly: true
      volumes:
      - name: headless-tls-volume
        secret:
          secretName: gateway-collector-headless-tls
      - name: otlp-ca-volume
        configMap:
          name: gateway-collector-otlp-ca
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 50Mi
      config: |
        # Multi-cluster client gateway configuration
        extensions:
          memory_ballast:
            size_in_percentage: 30
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
                tls:
                  cert_file: /headless-tls/tls.crt
                  key_file: /headless-tls/tls.key
        processors:
          attributes:
            actions:
              - key: k8s.cluster.name
                action: insert
                value: "<client-cluster-name>"
          batch:
          memory_limiter:
            check_interval: 1s
            limit_percentage: 80
            spike_limit_percentage: 25
        exporters:
          otlp:
            endpoint: otlp.<server-cluster-domain>:443
            tls:
              ca_file: /otlp-ca/ca.crt
            headers:
              Authorization: "Basic <auth-token>"
        service:
          extensions: [memory_ballast]
          pipelines:
            traces:
              receivers: [otlp]
              processors: [memory_limiter, attributes, batch]
              exporters: [otlp]
